---
Hosts:
  'spyweb1':
    IP   : 10.0.2.11
    graph: 
      - system
      - nginx
      - apache
    tree : LEMP

  'spybdd1':
    IP   : 10.0.2.51
    graph:
      - system
      - mysql
      - memcache
      - redis
      - mongodb
    tree : Mysql
    notes: 'Database Server'

  'spycache1':
    IP   : 10.0.2.16
    graph: 
      - system
      - varnish
      - memcache
      - galera
    tree : Varnish
    notes: 'Cache Server'

  'spywatch':
    IP   : 10.0.2.40
    graph: 
      - system
      - elasticsearch
      - redis
    tree : ES
    notes: 'Elasticsearch server'

  'spymail':
    IP   : 10.0.2.70
    graph: 
      - system
      - postfix
    tree : Mail
    notes: 'Mail Server'
